project:
  type: website
  output-dir: _site

website:
  title: "Shader Programming"

  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - index.qmd
      - section: "3D Rendering"
        contents:
          - text: "First Rays"
            href: notes/3d/first-rays/notes.qmd
          - text: "Raymarching"
            href: notes/3d/raymarching/notes.qmd
          - text: "Deriving SDFs"
            href: notes/3d/deriving-sdfs/notes.qmd
          - text: "SDF Library"
            href: notes/3d/sdf-library/notes.qmd
          - text: "Sculpting"
            href: notes/3d/sculpting/notes.qmd
          - text: "Lighting & Shadows"
            href: notes/3d/lighting-shadows/notes.qmd
          - text: "Materials"
            href: notes/3d/materials/notes.qmd
          - text: "Refraction"
            href: notes/3d/refraction/notes.qmd
          - text: "Procedural Patterns"
            href: notes/3d/procedural/notes.qmd

      # - section: "Fundamentals"
      #   contents:
      #     - fundamentals/coordinates.qmd
      #     - fundamentals/colors.qmd
      - text: "---"
      - text: "CIRM 2026"
        href: /cirm-2026/

# Shared metadata
author: "Steve Trettel"

highlight-style: arrow

format:
  html:
    theme:
      light: [cosmo, styles/website.scss]
      dark: [darkly, styles/website.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    number-sections: false
    link-external-newwindow: true
    smooth-scroll: true
