/**
 * Stage 3a: AST → LaTeX a human would have written.
 *
 * Deliberately ignores every number the resolver computed: the output uses
 * \label / \cref / \eqref and lets LaTeX count natively, so the .tex is
 * publisher-clean — renumber, reorder, or restyle it and nothing breaks.
 * The aux check verifies LaTeX's numbers match the resolver's.
 */

import { environments, proofLike } from "./registry.js";

const WRAP = 88;

export function emitMain(book, chapters) {
  const styles = { plain: [], definition: [], remark: [] };
  for (const [name, env] of Object.entries(environments)) styles[env.style].push(name);

  const theoremDecls = [];
  let first = true;
  for (const [style, names] of Object.entries(styles)) {
    theoremDecls.push(`\\theoremstyle{book${style}}`); // styles defined in the preamble
    for (const name of names) {
      const word = capitalize(environments[name].word);
      theoremDecls.push(
        first
          ? `\\newtheorem{${name}}{${word}}[chapter]`
          : `\\newtheorem{${name}}[theorem]{${word}}`
      );
      first = false;
    }
  }

  const includes = [];
  for (const part of book.parts) {
    if (part.figure) includes.push(`\\BookPartFig{figures/${part.figure}.pdf}`);
    if (part.title) includes.push(`\\part{${escapeText(part.title)}}`);
    for (const ch of part.chapters) includes.push(`\\include{${ch.slug}}`);
  }

  return `% Generated by the compiler — do not edit. The hand-authored print design
% lives in latex/preamble/preamble.tex; this file carries only what the
% environment registry and book.yml derive.
\\documentclass[12pt]{memoir}

\\def\\BookTitle{${escapeText(book.title)}}
\\def\\BookAuthor{${escapeText(book.author)}}
\\def\\BookBlurb{${escapeText(book.blurb ?? "")}}
\\def\\BookHeroFig{${book.figure ? `\\includegraphics[width=\\textwidth]{figures/${book.figure}.pdf}` : ""}}
\\input{../preamble/preamble}
\\input{../macros}% THE shared macro file — math.js feeds the same file to MathJax

% Reference words pinned to match the website's (cleveref abbreviates
% "figure" to "fig." by default; the two outputs must read identically).
\\crefname{figure}{figure}{figures}
\\crefname{chapter}{chapter}{chapters}
\\crefname{section}{section}{sections}

\\numberwithin{equation}{chapter}

${theoremDecls.join("\n")}

\\newenvironment{sketch}{\\begin{proof}[Sketch]}{\\end{proof}}

\\begin{document}

\\frontmatter
\\BookTitlePage
\\cleardoublepage
\\tableofcontents*

\\mainmatter

${includes.join("\n")}

\\end{document}
`;
}

export function emitChapter(ch) {
  return blocks(ch.tree.children) + "\n";
}

/**
 * Source adjacency is preserved: a $$ block written flush against prose (no
 * blank line) emits with no blank line, so the equation sits inside its
 * paragraph and the following text is a continuation, not a new (indented)
 * paragraph — exactly how a human writes displayed math in TeX.
 */
function blocks(nodes) {
  const parts = [];
  let prev = null;
  for (const node of nodes) {
    const text = block(node);
    if (text === null) continue;
    if (prev) {
      const adjacent =
        prev.position && node.position && node.position.start.line - prev.position.end.line === 1;
      parts.push(adjacent ? "\n" : "\n\n");
    }
    parts.push(text);
    prev = node;
  }
  return parts.join("");
}

function block(node) {
  switch (node.type) {
    case "yaml":
      return null;
    case "heading":
      return heading(node);
    case "paragraph":
      return wrap(inline(node.children));
    case "math":
      return displayMath(node);
    case "containerDirective":
      return directive(node);
    case "list":
      return list(node);
    case "blockquote":
      return `\\begin{quote}\n${indent(blocks(node.children))}\n\\end{quote}`;
    case "thematicBreak":
      return "\\bigskip";
    default:
      throw new Error(`latex emitter: unhandled block node "${node.type}"`);
  }
}

const HEADING_CMD = { 1: "chapter", 2: "section", 3: "subsection", 4: "subsubsection" };

function heading(node) {
  const cmd = HEADING_CMD[node.depth];
  if (!cmd) throw new Error(`latex emitter: heading depth ${node.depth} unsupported`);
  const star = node.data?.unnumbered ? "*" : "";
  const label = node.data?.id ? `\n\\label{${node.data.id}}` : "";
  return `\\${cmd}${star}{${inline(node.children)}}${label}`;
}

function displayMath(node) {
  const body = node.value.trim();
  if (!node.data?.id) return `\\[\n${indent(body)}\n\\]`;
  return `\\begin{equation}\n\\label{${node.data.id}}\n${indent(body)}\n\\end{equation}`;
}

function directive(node) {
  const inner = blocks(node.children);
  if (proofLike[node.name])
    return `\\begin{${node.name}}\n${inner}\n\\end{${node.name}}`;

  if (node.name === "figure") return figure(node, inner);

  const title = node.attributes?.title ? `[${escapeText(node.attributes.title)}]` : "";
  const label = node.attributes?.id ? `\n\\label{${node.attributes.id}}` : "";
  return `\\begin{${node.name}}${title}${label}\n${inner}\n\\end{${node.name}}`;
}

function figure(node, caption) {
  // The captured print still, copied to latex/build/figures/ by the build.
  const label = node.attributes?.id ? `\n  \\label{${node.attributes.id}}` : "";
  return [
    "\\begin{figure}[tbp]",
    "  \\centering",
    `  \\includegraphics[width=0.85\\textwidth]{figures/${node.attributes.id}.pdf}`,
    `  \\caption{${caption}}${label}`,
    "\\end{figure}",
  ].join("\n");
}

function list(node) {
  const env = node.ordered ? "enumerate" : "itemize";
  const items = node.children
    .map((li) => `  \\item ${blocks(li.children)}`)
    .join("\n");
  return `\\begin{${env}}\n${items}\n\\end{${env}}`;
}

function inline(nodes) {
  return nodes.map(inlineOne).join("");
}

function inlineOne(node) {
  switch (node.type) {
    case "text":
      return escapeText(node.value);
    case "inlineMath":
      return `$${node.value}$`;
    case "emphasis":
      return `\\emph{${inline(node.children)}}`;
    case "strong":
      return `\\textbf{${inline(node.children)}}`;
    case "inlineCode":
      return `\\texttt{${escapeText(node.value)}}`;
    case "ref":
      return ref(node);
    case "link":
      return `\\href{${node.url}}{${inline(node.children)}}`;
    case "break":
      return "\\\\\n";
    default:
      throw new Error(`latex emitter: unhandled inline node "${node.type}"`);
  }
}

function ref(node) {
  if (node.resolved?.kind === "equation") return `\\eqref{${node.target}}`;
  return `\\${node.capitalized ? "Cref" : "cref"}{${node.target}}`;
}

const ESCAPES = {
  "\\": "\\textbackslash{}",
  "&": "\\&",
  "%": "\\%",
  "$": "\\$",
  "#": "\\#",
  "_": "\\_",
  "{": "\\{",
  "}": "\\}",
  "~": "\\textasciitilde{}",
  "^": "\\textasciicircum{}",
};

function escapeText(text) {
  return text.replace(/[\\&%$#_{}~^]/g, (c) => ESCAPES[c]);
}

function capitalize(word) {
  return word[0].toUpperCase() + word.slice(1);
}

function indent(text) {
  return text.replace(/^/gm, "  ");
}

/** Soft-wrap a paragraph at word boundaries so the .tex reads like prose. */
function wrap(text) {
  const out = [];
  for (const hard of text.split("\n")) {
    let line = "";
    for (const word of hard.split(" ")) {
      if (line && line.length + word.length + 1 > WRAP) {
        out.push(line);
        line = word;
      } else {
        line = line ? `${line} ${word}` : word;
      }
    }
    out.push(line);
  }
  return out.join("\n");
}
